---
apiVersion: v2
name: argo-istio
type: application
version: 1.0
appVersion: 1.12.1
dependencies:
- name: istio-operator
  version: "2.0.5"
  repository: "https://kubernetes-charts.banzaicloud.com/"







