apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-operator
  annotations:
    argocd.argoproj.io/sync-wave: "-40"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: ''
    namespace: istio-operator
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: 'https://wiremind.github.io/wiremind-helm-charts'
    targetRevision: 1.12.0
    chart: istio-operator
  project: default
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: false
      selfHeal: false

