apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-ingress
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
spec:
  destination:
    name: ''
    namespace: istio-system
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: 'https://istio-release.storage.googleapis.com/charts'
    targetRevision: 1.12.1
    chart: gateway
  project: default
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true

