apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio
  annotations:
    argocd.argoproj.io/sync-wave: "-30"
spec:
  destination:
    name: ''
    namespace: istio-system
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: 'https://kubernetes-charts.banzaicloud.com/'
    targetRevision: 1.0.5
    chart: istio
  project: default
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
