apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-cfg
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/aheritier-csgroup/argocd.git
    targetRevision: HEAD
    path: istio-cfg
  destination: 
    server: https://kubernetes.default.svc
    namespace: istio-operator

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
