apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  project: default

  source:
    repoURL: https://github.com/aheritier-csgroup/argocd.git
    targetRevision: HEAD
    path: istio-operator/
  destination: 
    server: https://kubernetes.default.svc
    namespace: istio-operator

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
