apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: namespaces
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
spec:
  project: default

  source:
    repoURL: https://github.com/aheritier-csgroup/argocd.git
    targetRevision: HEAD
    path: namespaces
  destination: 
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    syncOptions:
    - CreateNamespace=false

    automated:
      selfHeal: true
      allowEmpty: true
      prune: true
