apiVersion: v1
kind: Secret
metadata:
  name: istio-helm-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://storage.googleapis.com/istio-prerelease/daily-build/master-latest-daily/charts
  name: istio.io
  type: helm
