---
apiVersion: v2
name: argo-istio-operator
type: application
version: 1.0
appVersion: 2.0.5
dependencies:
- name: istio-operator
  version: "2.0.5" 
  repository: "https://kubernetes-charts.banzaicloud.com"

