apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mettallb
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-50"
spec:
  project: default

  source:
    repoURL: https://github.com/aheritier-csgroup/argocd.git
    targetRevision: HEAD
    path: metallb
  destination: 
    server: https://kubernetes.default.svc
    namespace: metallb-system

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
